
#!/bin/bash
# =============================================
# 🧹 LaTeX Cleanup Script
# Clean auxiliary and temporary files generated by LaTeX
# =============================================

MAIN_FILE="main"  # main file name (without extension)

# --- Phase 1: Start cleanup ---
echo -e "\n\033[1;34m🧹 Cleaning auxiliary files...\033[0m"

# Remove common auxiliary files
rm -f "$MAIN_FILE".{aux,bbl,bcf,blg,lof,log,lot,out,toc,run.xml}

# Remove generic LaTeX build files
rm -f *.spl *.synctex.gz *.fls *.fdb_latexmk

# Remove minted temporary data
rm -rf "_minted-$MAIN_FILE" *.pygtex

# --- Phase 2: Confirmation ---
echo -e "\033[1;32m✅ Cleanup complete!\033[0m"
echo -e "\033[1;90mAll temporary files removed safely.\033[0m\n"
